apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      serviceAccountName: react-ui-service-ksa
      containers:
      - name: react-ui
        image: us-central1-docker.pkg.dev/swe590-project-458808/react-ui/react-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui-service
spec:
  type: LoadBalancer
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80